### ISSUE TITLE
How to use this plugin

### ISSUE THREAD

**Issue by gnykumar** [ros-simulation/gazebo_radar_plugin#4] opened 2018-12-03 06:35 UTC
what is sensor type is should use
Like

for laser/lidar  `<sensor type="ray" name="laser">`
for camera `<sensor type="camera" name="camera">`
for kinect `<sensor type="depth" name="kinect">`
same for radar
`<sensor type="???????" name="radar">`

**Comment by tfoote** [comment] 2018-12-03 19:48
Duplicate of #2 please see that for an example.

**Closed as completed by tfoote** 2018-12-03 19:48 UTC

**Comment by gnykumar** [comment] 2018-12-04 13:23
@tfoote Thanks, i used as it mention am facing with error 
Unpause physics service call failed: unable to connect to service: [Errno 104] Connection reset by peer
Segmentation fault (core dumped)

Please let me know is anyone used this plugin already and working

**Comment by gnykumar** [comment] 2018-12-06 06:05
@tfoote 
Sensor type ="logical_camera" is not working with libModeCRadarPlugin.so, gazebo process die with error i mentioned above.

Sensor type="radar" doesn't give any data with libModeCRadarPlugin, but gazebo is just running
